# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ct_condition_cla <- function(y, t, ll, mm, Q, method, atol, rtol) {
    .Call(`_lemad_ct_condition_cla`, y, t, ll, mm, Q, method, atol, rtol)
}

cla_calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, method, atol, rtol, is_complete_tree) {
    .Call(`_lemad_cla_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, method, atol, rtol, is_complete_tree)
}

calc_cla_ll_threaded <- function(ances, states_R, forTime_R, lambdas_R, mus_R, Q, num_threads = 1L, method = "odeint::bulirsch_stoer", is_complete_tree = FALSE) {
    .Call(`_lemad_calc_cla_ll_threaded`, ances, states_R, forTime_R, lambdas_R, mus_R, Q, num_threads, method, is_complete_tree)
}

calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, num_threads, abstol, reltol, method, is_complete_tree) {
    .Call(`_lemad_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, num_threads, abstol, reltol, method, is_complete_tree)
}

ct_condition <- function(y, t, ll, mm, Q, method, atol, rtol) {
    .Call(`_lemad_ct_condition`, y, t, ll, mm, Q, method, atol, rtol)
}

calc_ll_threaded <- function(ll, mm, Q, ances, for_time, states, num_threads, method = "odeint::bulirsch_stoer", is_complete_tree = FALSE) {
    .Call(`_lemad_calc_ll_threaded`, ll, mm, Q, ances, for_time, states, num_threads, method, is_complete_tree)
}

